#%RAML 1.0
---

title: Apprenticeship Levy
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml
  types: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/types.raml

traits:
  successResponse:
    responses:
      200:
        body:
          application/json:
            type: <<responseSchema>>
            examples:
              example-1:
                value: <<successExample>>
      401:
        body:
          application/json:
            type: <<responseSchema>>
            examples:
              example-1:
                value: <<successExample>>

annotationTypes:
  config: object
  group:
    type: object
    properties:
      name: string
      description: string
  scope:

/apprenticeship-levy:
  /:
    get:
      displayName: Get all employers
      description: !include docs/get-all-employers.md
      is: [headers.acceptHeader]
      (annotations.scope): "read:apprenticeship-levy"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:apprenticeship-levy" ] } ]
      (annotations.sandboxData): !include sandbox/get-all-employers.md
      headers: 
        Authorization:
          example: Bearer [token here]
      responses: 
        200:
          body:
            application/json:
              type: !include schemas/get-all-employers.json
              example: !include examples/get-all-employers.json
        400:
          body:
            application/json:
              type: types.errorResponse
              examples:
               400_AUTH_ERROR_BAD_REQUEST:
                 description: The request made is not valid.
                 value:
                   code: AUTH_ERROR_BAD_REQUEST
        401:
          body:
            application/json:
              type: types.errorResponse
              examples:
                401_INVALID_CREDENTIALS:
                  description: The request requires correct authentication headers with valid token.
                  value:
                    code: INVALID_CREDENTIALS
                401_AUTH_ERROR_UNAUTHORIZED:
                  description: The request requires user authentication. Please ensure Grant authority has been given and bearer token is supplied with the request headers.
                  value:
                    code: AUTH_ERROR_UNAUTHORIZED
        403:
          body:
            application/json:
              type: types.errorResponse
              examples:
                403_AUTH_ERROR_FORBIDDEN:
                  description: The request requires user authentication. Please ensure Grant authority has been given and bearer token is supplied with the request headers.
                  value:
                    code: AUTH_ERROR_FORBIDDEN
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                404_AUTH_ERROR_NOT_FOUND:
                  description: Endpoint or internal system has become unavailable.
                  value:
                    code: AUTH_ERROR_NOT_FOUND
        408:
          body:
            application/json:
              type: types.errorResponse
              examples:
                408_AUTH_ERROR_REQUEST_TIMEOUT:
                  description: Endpoint or internal system has become unresponsive.
                  value:
                    code: AUTH_ERROR_REQUEST_TIMEOUT
                408_AUTH_ERROR_GATEWAY_TIMEOUT:
                  description: Endpoint or internal system has become unresponsive.
                  value:
                    code: AUTH_ERROR_GATEWAY_TIMEOUT
        409:
          body:
            application/json:
              type: types.errorResponse
              examples:
                409_AUTH_ERROR_TOO_MANY_REQUESTS:
                  description: Endpoint API has experienced too many requests.
                  value:
                    code: AUTH_ERROR_TOO_MANY_REQUESTS
        498:
          body:
            application/json:
              type: types.errorResponse
              examples:
                498_AUTH_ERROR_WRONG_TOKEN:
                  description: Endpoint or internal system has experienced an internal error.
                  value:
                    code: AUTH_ERROR_WRONG_TOKEN
        500:
          body:
            application/json:
              type: types.errorResponse
              examples:
                500_AUTH_ERROR_INTERNAL_SERVER_ERROR:
                  description: Endpoint API has experienced an internal error.
                  value:
                    code: AUTH_ERROR_INTERNAL_SERVER_ERROR
        503:
          body:
            application/json:
              type: types.errorResponse
              examples:
                503_AUTH_ERROR_BACKEND_FAILURE:
                  description: Endpoint or internal system has experienced an internal error.
                  value:
                    code: AUTH_ERROR_BACKEND_FAILURE
                503_AUTH_ERROR_OTHER:
                  description: Endpoint or internal system has experienced an internal error.
                  value:
                    code: AUTH_ERROR_OTHER
                503_AUTH_ERROR_IO:
                  description: Endpoint API has experienced IO failure
                  value:
                    code: AUTH_ERROR_IO
  /epaye:
    /{empref}:
      uriParameters:
        empref:
          description: A valid (URL encoded) employer reference for the PAYE scheme.
          type: string
          example: 123/AB12345
      get:
          displayName: Get employer details
          description: !include docs/get-employer-details.md
          is: [headers.acceptHeader]
          (annotations.scope): "read:apprenticeship-levy"
          securedBy: [ sec.oauth_2_0: { scopes: [ "read:apprenticeship-levy" ] } ]
          (annotations.sandboxData): !include sandbox/get-employer-details.md
          headers: 
            Authorization:
              example: Bearer [token here]
          responses: 
            200:
              body:
                application/json:
                  type: !include schemas/get-employer-details.json
                  example: !include examples/get-employer-details.json
            400:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    400_EMPREF_INVALID:
                      description: A request parameter is incorrect.
                      value:
                        code: EMPREF_INVALID
                    400_AUTH_ERROR_BAD_REQUEST:
                      description: The request made is not valid.
                      value:
                        code: AUTH_ERROR_BAD_REQUEST
                    400_DES_ERROR_BAD_REQUEST:
                      description: The request made is not valid.
                      value:
                        code: DES_ERROR_BAD_REQUEST
            401:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    401_INVALID_CREDENTIALS:
                      description: The request requires correct authentication headers with valid token.
                      value:
                        code: INVALID_CREDENTIALS
                    401_AUTH_ERROR_UNAUTHORIZED:
                      description: The request requires user authentication. Please ensure Grant authority has been given and bearer token is supplied with the request headers.
                      value:
                        code: AUTH_ERROR_UNAUTHORIZED
                    401_DES_ERROR_UNAUTHORIZED:
                      description: The request requires user authentication. Please ensure Grant authority has been given and bearer token is supplied with the request headers.
                      value:
                        code: DES_ERROR_UNAUTHORIZED
            403:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    403_AUTH_ERROR_FORBIDDEN:
                      description: The request requires user authentication. Please ensure Grant authority has been given and bearer token is supplied with the request headers.
                      value:
                        code: AUTH_ERROR_FORBIDDEN
                    403_DES_ERROR_FORBIDDEN:
                      description: The request requires user authentication. Please ensure Grant authority has been given and bearer token is supplied with the request headers.
                      value:
                        code: DES_ERROR_FORBIDDEN
            404:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    404_EPAYE_EMPREF_UNKNOWN:
                      description: Employer reference is unknown or endpoint not found.
                      value:
                        code: EPAYE_EMPREF_UNKNOWN
                    404_AUTH_ERROR_NOT_FOUND:
                      description: Endpoint or internal system has become unavailable.
                      value:
                        code: AUTH_ERROR_NOT_FOUND
                    404_DES_ERROR_NOT_FOUND:
                      description: Endpoint or internal system has become unavailable.
                      value:
                        code: DES_ERROR_NOT_FOUND
            408:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    408_AUTH_ERROR_REQUEST_TIMEOUT:
                      description: Endpoint or internal system has become unresponsive.
                      value:
                        code: AUTH_ERROR_REQUEST_TIMEOUT
                    408_AUTH_ERROR_GATEWAY_TIMEOUT:
                      description: Endpoint or internal system has become unresponsive.
                      value:
                        code: AUTH_ERROR_GATEWAY_TIMEOUT
                    408_DES_ERROR_GATEWAY_TIMEOUT:
                      description: Endpoint or internal system has become unresponsive.
                      value:
                        code: DES_ERROR-GATEWAY_TIMEOUT
            429:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    429_AUTH_ERROR_TOO_MANY_REQUESTS:
                      description: Too many requests have been made to this endpoint
                      value:
                        code: AUTH_ERROR_TOO_MANY_REQUESTS
                    429_DES_ERROR_TOO_MANY_REQUESTS:
                      description: Too many requests have been made to this endpoint
                      value:
                        code: DES_ERROR_TOO_MANY_REQUESTS
            500:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    500_AUTH_ERROR_INTERNAL_SERVER_ERROR:
                      description: Endpoint API has experienced an internal error.
                      value:
                        code: AUTH_ERROR_INTERNAL_SERVER_ERROR
                    500_DES_ERROR_JSON_FAILURE:
                      description: Endpoint API has returned invalid JSON.
                      value:
                        code: DES_ERROR_JSON_FAILURE
                    500_DES_ERROR_API:
                      description: Endpoint API has experienced an internal error.

            503:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    503_AUTH_ERROR_BACKEND_FAILURE:
                      description: Endpoint or internal system has experienced an internal error.
                      value:
                        code: AUTH_ERROR_BACKEND_FAILURE
                    503_AUTH_ERROR_OTHER:
                      description: Endpoint or internal system has experienced an internal error.
                      value:
                        code: AUTH_ERROR_OTHER
                    503_AUTH_ERROR_IO:
                      description: Endpoint API has experienced IO failure
                      value:
                        code: AUTH_ERROR_IO
                    503_DES_ERROR_BACKEND_FAILURE:
                      description: Endpoint or internal system has experienced an internal error.
                      value:
                        code: DES_ERROR_BACKEND_FAILURE
                     503_DES_ERROR_OTHER:
                       description: Endpoint or internal system has experienced an internal error.
                       value:
                         code: DES_ERROR_OTHER
                    503_DES_ERROR_IO:
                      description: Endpoint API has experienced IO failure
                      value:
                        code: DES_ERROR_IO
      /declarations:
        get:
          displayName: Get employer levy declarations
          description: !include docs/get-employer-levy-declarations.md
          is: [headers.acceptHeader]
          (annotations.scope): "read:apprenticeship-levy"
          securedBy: [ sec.oauth_2_0: { scopes: [ "read:apprenticeship-levy" ] } ]
          (annotations.sandboxData): !include sandbox/get-employer-levy-declarations.md
          headers: 
            Authorization:
              example: Bearer [token here]
          queryParameters: 
            fromDate: 
              description: The date of the earliest record to return. If no date is supplied the default date of current month/year - 6 years will be used.
              type: date-only
              example: 2015-08-09
              required: false
            toDate: 
              description: The date of the latest record to return. If no date is supplied the default date of 'now'/'today' will be used.
              type: date-only
              example: 2015-08-09
              required: false
          responses: 
            200:
              body:
                application/json:
                  type: !include schemas/get-employer-levy-declarations.json
                  example: !include examples/get-employer-levy-declarations.json
            400:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    400_EMPREF_INVALID:
                      description: Employer reference (EMPREF) request parameter is incorrect.
                      value:
                        code: EMPREF_INVALID
                    400_DATE_INVALID:
                      description: Date(s) request parameter(s) is incorrect.
                      value:
                        code: DATE_INVALID
                    400_AUTH_ERROR_BAD_REQUEST:
                      description: The request made is not valid.
                      value:
                        code: AUTH_ERROR_BAD_REQUEST
                    400_DES_ERROR_BAD_REQUEST:
                      description: The request made is not valid.
                      value:
                        code: DES_ERROR_BAD_REQUEST

            401:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    401_INVALID_CREDENTIALS:
                      description: The request requires correct authentication headers with valid token.
                      value:
                        code: INVALID_CREDENTIALS
                    401_AUTH_ERROR_UNAUTHORIZED:
                      description: The request requires user authentication. Please ensure Grant authority has been given and bearer token is supplied with the request headers.
                      value:
                        code: AUTH_ERROR_UNAUTHORIZED
                    401_DES_ERROR_UNAUTHORIZED:
                      description: The request requires user authentication. Please ensure Grant authority has been given and bearer token is supplied with the request headers.
                      value:
                        code: DES_ERROR_UNAUTHORIZED
            403:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    403_AUTH_ERROR_FORBIDDEN:
                      description: The request requires user authentication. Please ensure Grant authority has been given and bearer token is supplied with the request headers.
                      value:
                        code: AUTH_ERROR_FORBIDDEN
                    403_DES_ERROR_FORBIDDEN:
                      description: The request requires user authentication. Please ensure Grant authority has been given and bearer token is supplied with the request headers.
                      value:
                        code: DES_ERROR_FORBIDDEN
            404:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    404_EPAYE_EMPREF_UNKNOWN:
                      description: Employer reference is unknown or endpoint not found.
                      value:
                        code: EPAYE_EMPREF_UNKNOWN
                    404_AUTH_ERROR_NOT_FOUND:
                      description: Endpoint or internal system has become unavailable.
                      value:
                        code: AUTH_ERROR_NOT_FOUND
                    404_DES_ERROR_NOT_FOUND:
                      description: Endpoint or internal system has become unavailable.
                      value:
                        code: DES_ERROR_NOT_FOUND
            408:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    408_AUTH_ERROR_REQUEST_TIMEOUT:
                      description: Endpoint or internal system has become unresponsive.
                      value:
                        code: AUTH_ERROR_REQUEST_TIMEOUT
                    408_AUTH_ERROR_GATEWAY_TIMEOUT:
                      description: Endpoint or internal system has become unresponsive.
                      value:
                        code: AUTH_ERROR_GATEWAY_TIMEOUT
                    408_DES_ERROR_GATEWAY_TIMEOUT:
                      description: Endpoint or internal system has become unresponsive.
                      value:
                        code: DES_ERROR-GATEWAY_TIMEOUT
            429:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    429_AUTH_ERROR_TOO_MANY_REQUESTS:
                      description: Too many requests have been made to this endpoint
                      value:
                        code: AUTH_ERROR_TOO_MANY_REQUESTS
                    429_DES_ERROR_TOO_MANY_REQUESTS:
                      description: Too many requests have been made to this endpoint
                      value:
                        code: DES_ERROR_TOO_MANY_REQUESTS
            500:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    500_AUTH_ERROR_INTERNAL_SERVER_ERROR:
                      description: Endpoint API has experienced an internal error.
                      value:
                        code: AUTH_ERROR_INTERNAL_SERVER_ERROR
                    500_DES_ERROR_JSON_FAILURE:
                      description: DES or backend system has returned invalid json which can not be relayed to API caller.
                      value:
                        code: DES_ERROR_JSON_FAILURE
                    500_DES_ERROR_BACKEND_FAILURE:
                      description: DES returned unexpected Json error response type on a HTTP 200 response.
                      value:
                        code: DES_ERROR_BACKEND_FAILURE
            503:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    503_AUTH_ERROR_BACKEND_FAILURE:
                      description: Endpoint or internal system has experienced an internal error.
                      value:
                        code: AUTH_ERROR_BACKEND_FAILURE
                    503_AUTH_ERROR_OTHER:
                      description: Endpoint or internal system has experienced an internal error.
                      value:
                        code: AUTH_ERROR_OTHER
                    503_AUTH_ERROR_IO:
                      description: Endpoint API has experienced IO failure
                      value:
                        code: AUTH_ERROR_IO
                    503_DES_ERROR_BACKEND_FAILURE:
                      description: Endpoint or internal system has experienced an internal error.
                      value:
                        code: DES_ERROR_BACKEND_FAILURE
                    503_DES_ERROR_OTHER:
                      description: Endpoint or internal system has experienced an internal error.
                      value:
                        code: DES_ERROR_OTHER
                    503_DES_ERROR_IO:
                      description: Endpoint API has experienced IO failure
                      value:
                        code: DES_ERROR_IO
      /fractions:
        get:
          displayName: Get employer fraction calculations
          description: !include docs/get-employer-fraction-calculations.md
          is: [headers.acceptHeader]
          (annotations.scope): "read:apprenticeship-levy"
          securedBy: [ sec.oauth_2_0: { scopes: [ "read:apprenticeship-levy" ] } ]
          (annotations.sandboxData): !include sandbox/get-employer-fraction-calculations.md
          headers: 
            Authorization:
              example: Bearer [token here]
          queryParameters: 
            fromDate: 
              description: The date of the earliest calculation to return. Defaults to 72 months prior to current date.
              type: date-only
              example: 2015-08-09
              required: false
            toDate: 
              description: The date of the latest calculation to return. Defaults to current date.
              type: date-only
              example: 2015-08-09
              required: false
          responses: 
            200:
              body:
                application/json:
                  type: !include schemas/get-employer-fraction-calculations.json
                  example: !include examples/get-employer-fraction-calculations.json
            400:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    400_EMPREF_INVALID:
                      description: Employer reference (EMPREF) request parameter is incorrect.
                      value:
                        code: EMPREF_INVALID
                    400_DATE_INVALID:
                      description: Date(s) request parameter(s) is incorrect.
                      value:
                        code: DATE_INVALID
                    400_AUTH_ERROR_BAD_REQUEST:
                      description: The request made is not valid.
                      value:
                        code: AUTH_ERROR_BAD_REQUEST
                    400_DES_ERROR_BAD_REQUEST:
                      description: The request made is not valid.
                      value:
                        code: DES_ERROR_BAD_REQUEST
            401:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    401_INVALID_CREDENTIALS:
                      description: The request requires correct authentication headers with valid token.
                      value:
                        code: INVALID_CREDENTIALS
                    401_AUTH_ERROR_UNAUTHORIZED:
                      description: The request requires user authentication. Please ensure Grant authority has been given and bearer token is supplied with the request headers.
                      value:
                        code: AUTH_ERROR_UNAUTHORIZED
                    401_DES_ERROR_UNAUTHORIZED:
                      description: The request requires user authentication. Please ensure Grant authority has been given and bearer token is supplied with the request headers.
                      value:
                        code: DES_ERROR_UNAUTHORIZED
            403:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    403_AUTH_ERROR_FORBIDDEN:
                      description: The request requires user authentication. Please ensure Grant authority has been given and bearer token is supplied with the request headers.
                      value:
                        code: AUTH_ERROR_FORBIDDEN
                    403_DES_ERROR_FORBIDDEN:
                      description: The request requires user authentication. Please ensure Grant authority has been given and bearer token is supplied with the request headers.
                      value:
                        code: DES_ERROR_FORBIDDEN
            404:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    404_EPAYE_EMPREF_UNKNOWN:
                      description: Endpoint or internal system has become unavailable.
                      value:
                        code: EPAYE_EMPREF_UNKNOWN
                    404_AUTH_ERROR_NOT_FOUND:
                      description: Endpoint or internal system has become unavailable.
                      value:
                        code: AUTH_ERROR_NOT_FOUND
                    404_DES_ERROR_NOT_FOUND:
                      description: Endpoint or internal system has become unavailable.
                      value:
                        code: DES_ERROR_NOT_FOUND
            408:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    408_AUTH_ERROR_REQUEST_TIMEOUT:
                      description: Endpoint or internal system has become unresponsive.
                      value:
                        code: AUTH_ERROR_REQUEST_TIMEOUT
                    408_AUTH_ERROR_GATEWAY_TIMEOUT:
                      description: Endpoint or internal system has become unresponsive.
                      value:
                        code: AUTH_ERROR_GATEWAY_TIMEOUT
                    408_DES_ERROR_GATEWAY_TIMEOUT:
                      description: Endpoint or internal system has become unresponsive.
                      value:
                        code: DES_ERROR-GATEWAY_TIMEOUT
            429:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    429_AUTH_ERROR_TOO_MANY_REQUESTS:
                      description: Too many requests have been made to this endpoint
                      value:
                        code: AUTH_ERROR_TOO_MANY_REQUESTS
                    429_DES_ERROR_TOO_MANY_REQUESTS:
                      description: Too many requests have been made to this endpoint
                      value:
                        code: DES_ERROR_TOO_MANY_REQUESTS
            500:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    500_AUTH_ERROR_INTERNAL_SERVER_ERROR:
                      description: Endpoint API has experienced an internal error.
                      value:
                        code: AUTH_ERROR_INTERNAL_SERVER_ERROR
                    500_DES_ERROR_JSON_FAILURE:
                      description: DES or backend system has returned invalid json which can not be relayed to API caller.
                      value:
                        code: DES_ERROR_JSON_FAILURE
                    500_DES_ERROR_BACKEND_FAILURE:
                      description: DES returned unexpected Json error response type on a HTTP 200 response.
                      value:
                        code: DES_ERROR_BACKEND_FAILURE
            503:
              body:
                application/json:
                  type: types.errorResponse
                  examples:
                    503_AUTH_ERROR_BACKEND_FAILURE:
                      description: Endpoint or internal system has experienced an internal error.
                      value:
                        code: AUTH_ERROR_BACKEND_FAILURE
                    503_AUTH_ERROR_OTHER:
                      description: Endpoint or internal system has experienced an internal error.
                      value:
                        code: AUTH_ERROR_OTHER
                    503_AUTH_ERROR_IO:
                      description: Endpoint API has experienced IO failure
                      value:
                        code: AUTH_ERROR_IO
                    503_DES_ERROR_BACKEND_FAILURE:
                      description: Endpoint or internal system has experienced an internal error.
                      value:
                        code: DES_ERROR_BACKEND_FAILURE
                    503_DES_ERROR_OTHER:
                      description: Endpoint or internal system has experienced an internal error.
                      value:
                        code: DES_ERROR_OTHER
                    503_DES_ERROR_IO:
                      description: Endpoint API has experienced IO failure
                      value:
                        code: DES_ERROR_IO
      /employed:
        /{nino}:
          uriParameters:
            nino:
              description: A valid National Insurance Number (nino) for the individual being checked.
              type: string
              example: XY654321Z
          get:
            displayName: Get employment status
            description: !include docs/get-employment-status.md
            is: [headers.acceptHeader]
            (annotations.scope): "read:apprenticeship-levy"
            securedBy: [ sec.oauth_2_0: { scopes: [ "read:apprenticeship-levy" ] } ]
            (annotations.sandboxData): !include sandbox/get-employment-status.md
            headers: 
              Authorization:
                example: Bearer [token here]
            queryParameters: 
              fromDate: 
                description: Starting date of the period to check employment for.
                type: date-only
                example: 2016-01-31
                required: true
              toDate: 
                description: Ending date of the period to check employment for.
                type: date-only
                example: 2016-01-31
                required: true
            responses: 
              200:
                body:
                  application/json:
                    type: !include schemas/get-employment-status.json
                    example: !include examples/get-employment-status.json
              400:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      400_EMPREF_INVALID:
                        description: Employer reference (EMPREF) request parameter is incorrect.
                        value:
                          code: EMPREF_INVALID
                      400_DATE_INVALID:
                        description: Date request parameter is incorrect.
                        value:
                          code: DATE_INVALID
                      400_NINO_INVALID:
                        description: Nino request parameter is incorrect
                        value:
                          code: NINO_INVALID
                      400_AUTH_ERROR_BAD_REQUEST:
                        description: The request made is not valid.
                        value:
                          code: AUTH_ERROR_BAD_REQUEST
                      400_DES_ERROR_BAD_REQUEST:
                        description: The request made is not valid.
                        value:
                          code: DES_ERROR_BAD_REQUEST
              401:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      401_INVALID_CREDENTIALS:
                        description: The request requires correct authentication headers with valid token.
                        value:
                          code: INVALID_CREDENTIALS
                      401_AUTH_ERROR_UNAUTHORIZED:
                        description: The request requires user authentication. Please ensure Grant authority has been given and bearer token is supplied with the request headers.
                        value:
                          code: AUTH_ERROR_UNAUTHORIZED
                        401_DES_ERROR_UNAUTHORIZED:
                          description: The request requires user authentication. Please ensure Grant authority has been given and bearer token is supplied with the request headers.
                          value:
                            code: DES_ERROR_UNAUTHORIZED
              403:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      403_AUTH_ERROR_FORBIDDEN:
                        description: The request requires user authentication. Please ensure Grant authority has been given and bearer token is supplied with the request headers.
                        value:
                          code: AUTH_ERROR_FORBIDDEN
                      403_DES_ERROR_FORBIDDEN:
                        description: The request requires user authentication. Please ensure Grant authority has been given and bearer token is supplied with the request headers.
                        value:
                          code: DES_ERROR_FORBIDDEN
              404:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      404_EPAYE_UNKNOWN:
                        description: Endpoint or internal system has become unavailable or either NINO or EMPREF are not found. EPAYE_NINO_UNKNOWN and EPAYE_EMPREF_UNKNOWN have been withdrawn as backend systems will not distinguish 404 errors between unknown NINO or unknown EMPREF.
                        value:
                          code: EPAYE_UNKNOWN
                      404_AUTH_ERROR_NOT_FOUND:
                        description: Endpoint or internal system has become unavailable.
                        value:
                          code: AUTH_ERROR_NOT_FOUND
                      404_DES_ERROR_NOT_FOUND:
                        description: Endpoint or internal system has become unavailable.
                        value:
                          code: DES_ERROR_NOT_FOUND
              408:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      408_AUTH_ERROR_REQUEST_TIMEOUT:
                        description: Endpoint or internal system has become unresponsive.
                        value:
                          code: AUTH_ERROR_REQUEST_TIMEOUT
                      408_AUTH_ERROR_GATEWAY_TIMEOUT:
                        description: Endpoint or internal system has become unresponsive.
                        value:
                          code: AUTH_ERROR_GATEWAY_TIMEOUT
                      408_DES_ERROR_GATEWAY_TIMEOUT:
                        description: Endpoint or internal system has become unresponsive.
                        value:
                          code: DES_ERROR-GATEWAY_TIMEOUT
              429:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      429_AUTH_ERROR_TOO_MANY_REQUESTS:
                        description: Too many requests have been made to this endpoint
                        value:
                          code: AUTH_ERROR_TOO_MANY_REQUESTS
                      429_DES_ERROR_TOO_MANY_REQUESTS:
                        description: Too many requests have been made to this endpoint
                        value:
                          code: DES_ERROR_TOO_MANY_REQUESTS
              500:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      500_AUTH_ERROR_INTERNAL_SERVER_ERROR:
                        description: Endpoint API has experienced an internal error.
                        value:
                          code: AUTH_ERROR_INTERNAL_SERVER_ERROR
                      500_DES_ERROR_JSON_FAILURE:
                        description: DES or backend system has returned invalid json which can not be relayed to API caller.
                        value:
                          code: DES_ERROR_JSON_FAILURE
                      500_DES_ERROR_BACKEND_FAILURE:
                        description: DES returned unexpected Json error response type on a HTTP 200 response
                        value:
                          code: DES_ERROR_BACKEND_FAILURE
              503:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      503_AUTH_ERROR_BACKEND_FAILURE:
                        description: Endpoint or internal system has experienced an internal error.
                        value:
                          code: AUTH_ERROR_BACKEND_FAILURE
                      503_AUTH_ERROR_OTHER:
                        description: Endpoint or internal system has experienced an internal error.
                        value:
                          code: AUTH_ERROR_OTHER
                      503_AUTH_ERROR_IO:
                        description: Endpoint API has experienced IO failure
                        value:
                          code: AUTH_ERROR_IO
                      503_DES_ERROR_BACKEND_FAILURE:
                        description: Endpoint or internal system has experienced an internal error.
                        value:
                          code: DES_ERROR_BACKEND_FAILURE
                      503_DES_ERROR_OTHER:
                        description: Endpoint or internal system has experienced an internal error.
                        value:
                          code: DES_ERROR_OTHER
                      503_DES_ERROR_IO:
                        description: Endpoint API has experienced IO failure
                        value:
                          code: DES_ERROR_IO
  /fraction-calculation-date:
    get:
      displayName: Get latest fraction calculation date
      description: !include docs/get-latest-fraction-calculation-date.md
      is: [headers.acceptHeader]
      (annotations.scope): "read:apprenticeship-levy"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:apprenticeship-levy" ] } ]
      (annotations.sandboxData): !include sandbox/get-latest-fraction-calculation-date.md
      headers: 
        Authorization:
          example: Bearer [token here]
      responses: 
        200:
          body:
            application/json:
              type: !include schemas/get-latest-fraction-calculation-date.json
              example: !include examples/get-latest-fraction-calculation-date.json
        401:
          body:
            application/json:
              type: types.errorResponse
              examples:
                401_INVALID_CREDENTIALS:
                  description: The request requires correct authentication headers with valid token.
                  value:
                    code: INVALID_CREDENTIALS
                401_DES_ERROR_UNAUTHORIZED:
                  description: The request requires user authentication. Please ensure Grant authority has been given and bearer token is supplied with the request headers.
                  value:
                    code: DES_ERROR_UNAUTHORIZED
        403:
          body:
            application/json:
              type: types.errorResponse
              examples:
                403_DES_ERROR_FORBIDDEN:
                  description: The request requires user authentication. Please ensure Grant authority has been given and bearer token is supplied with the request headers.
                  value:
                    code: DES_ERROR_FORBIDDEN
        404:
          body:
            application/json:
              type: types.errorResponse
              examples:
                404_DES_ERROR_NOT_FOUND:
                  description: Endpoint or internal system has become unavailable.
                  value:
                    code: DES_ERROR_NOT_FOUND
        408:
          body:
            application/json:
              type: types.errorResponse
              examples:
                408_DES_ERROR_REQUEST_TIMEOUT:
                  description: Endpoint or internal system has become unresponsive.
                  value:
                    code: DES_ERROR_REQUEST_TIMEOUT
        429:
          body:
            application/json:
              type: types.errorResponse
              examples:
                429_DES_ERROR_TOO_MANY_REQUESTS:
                  description: Too many requests have been made to the back-end systems.
                  value:
                    code: DES_ERROR_TOO_MANY_REQUESTS
        500:
          body:
            application/json:
              type: types.errorResponse
              examples:
                500_DES_ERROR_API:
                  description: API has experienced an internal error.
                  value:
                    code: DES_ERROR_API
        503:
          body:
            application/json:
              type: types.errorResponse
              examples:
                503_DES_ERROR_IO:
                  description: Internal system has become unresponsive causing an IO error.
                  value:
                    code: DES_ERROR_IO
                503_DES_ERROR_OTHER:
                  description: Endpoint or internal system has experienced an internal error.
                  value:
                    code: DES_ERROR_OTHER
                503_DES_ERROR_BACKEND_FAILURE:
                  description: Backend has experiences a server 5xx error.
                  value:
                    code: DES_ERROR_BACKEND_FAILURE
