#%RAML 1.0
---

title: Apprenticeship Levy
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include http://api-documentation-raml-frontend.service/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include http://api-documentation-raml-frontend.service/api-documentation/assets/common/docs/errors.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/securitySchemes.raml
  headers: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/headers.raml
traits:
  successResponse:
    responses:
      200:
        body:
          application/json:
            type: <<responseSchema>>
            examples:
              example-1:
                value: <<successExample>>

annotationTypes:
  config: object
  group:
    type: object
    properties:
      name: string
      description: string
  scope:

/apprenticeship-levy:
  get:
    displayName: Get all employers
    description: Returns a list of valid links indexed by empref in HAL format
    is: [headers.acceptHeader]
    (scope): "read:apprenticeship-levy"
    securedBy: [ sec.oauth_2_0: { scopes: [ "read:apprenticeship-levy" ] } ]
    responses:
      200:
        body:
          application/json:
            examples:
              example-1:
                value: !include examples/root-example-1.json
  /epaye:
    /{empref}:
      uriParameters:
        empref:
          description: A valid (URL encoded) employer reference for the PAYE scheme.
          type: string
          example: 123/AB12345
      get:
        displayName: Get employer
        description: Returns more details about an empref including details about the employer and a list of available endpoints that apply to the empref.
        is: [headers.acceptHeader]
        (scope): "read:apprenticeship-levy"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:apprenticeship-levy" ] } ]
        responses:
          200:
            body:
              application/json:
                examples:
                  example-1:
                    value: !include examples/empref-example-1.json
      /declarations:
        get:
          displayName: Get employer levy declarations
          description: Returns a list of levy declarations for a given employer reference.
          is:
            - headers.acceptHeader
            - successResponse:
                successExample: !include examples/levy-declarations-example-1.json
                responseSchema: !include schemas/employer-levy-declarations.json
          (scope): "read:apprenticeship-levy"
          securedBy: [ sec.oauth_2_0: { scopes: [ "read:apprenticeship-levy" ] } ]
          queryParameters:
            fromDate:
              description: The date of the earliest record to return. Records that would fall into a tax year older than the current year - 6 will not be returned.
              type: date-only
              example: 2015-08-09
              required: false
            toDate:
              description: The date of the latest record to return.
              type: date-only
              example: 2015-08-09
              required: false
      /fractions:
        get:
          displayName: Get employer fraction calculations
          description: Returns a list of fraction calculations for a given employer reference.
          is: [headers.acceptHeader]
          (scope): "read:apprenticeship-levy"
          securedBy: [ sec.oauth_2_0: { scopes: [ "read:apprenticeship-levy" ] } ]
          queryParameters:
            fromDate:
              description: The date of the earliest calculation to return.
              type: date-only
              example: 2015-08-09
              required: false
            toDate:
              description: The date of the latest calculation to return.
              type: date-only
              example: 2015-08-09
              required: false
          responses:
            200:
              body:
                application/json:
                  examples:
                    example-1:
                      value: !include examples/fraction-calculations-example-1.json
      /employed:
        /{nino}:
          uriParameters:
            nino:
              description: A valid National Insurance Number (nino) for the individual being checked.
              type: string
              example: XY654321Z
          get:
            displayName: Get employment status
            description: Checks the employment status of an individual in a payroll scheme.
            is: [headers.acceptHeader]
            (scope): "read:apprenticeship-levy"
            securedBy: [ sec.oauth_2_0: { scopes: [ "read:apprenticeship-levy" ] } ]
            queryParameters:
              fromDate:
                description: Starting date of the period to check employment for.
                type: date-only
                example: 2016-01-31
                required: true
              toDate:
                description: Ending date of the period to check employment for.
                type: date-only
                example: 2016-01-31
                required: true
            responses:
              200:
                body:
                  application/json:
                    examples:
                      example-1:
                        value: !include examples/employment-check-example-1.json
  /fraction-calculation-date:
    get:
      displayName: Get latest fraction calculation date
      description: Returns the date of the most recent fraction calculation batch run.
      is: [headers.acceptHeader]
      (scope): "read:apprenticeship-levy"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:apprenticeship-levy" ] } ]
      responses:
        200:
          body:
            application/json:
              examples:
                example-1:
                  value: !include examples/fraction-calculation-date-example-1.json
